[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"